version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pqzada-website
    restart: always
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "33000:3000"
    networks:
      - pqzadaNetwork
    depends_on:
      - db
  db:
    image: mysql:8.0.19
    container_name: pqzada-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=pqzada
      - MYSQL_DATABASE=pqzada
      - MYSQL_USER=pqzada
      - MYSQL_PASSWORD=pqzada
    ports:
      - "33306:3306"
    networks:
      - pqzadaNetwork

networks:
  pqzadaNetwork:
    driver: bridge
